// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uifggdiglhltnvwthdqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpZmdnZGlnbGhsdG52d3RoZHFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzgyODEsImV4cCI6MjA2MTQxNDI4MX0.b8wXSLgQknONprb-q6w4hLO_6x12VcYqmbIpZ0BrKO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);